apiVersion: v1
kind: ConfigMap
metadata:
  name: grc-toolkit-config
  namespace: {{ include "grc-toolkit.namespace" . }}
  labels:
    {{- include "grc-toolkit.labels" . | nindent 4 }}
data:
  APP_NAME: {{ .Values.config.appName | quote }}
  APP_VERSION: {{ .Values.config.appVersion | quote }}
  APP_BUILD_DATE: {{ .Values.config.appBuildDate | default (now | date "2006-01-02") | quote }}
  FEATURE_PQC: {{ .Values.config.featurePqc | quote }}
